// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLzVhDqvWKTdgaV_0H2_nQ9wBRuTpydg',
    appId: '1:942862744242:web:cac1cecd14127613de27ab',
    messagingSenderId: '942862744242',
    projectId: 'multi-detection-system',
    authDomain: 'multi-detection-system.firebaseapp.com',
    storageBucket: 'multi-detection-system.firebasestorage.app',
    measurementId: 'G-0PGS6JP4V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHTRyk3nv6tMBTFts7JitkcKny5to0UG4',
    appId: '1:942862744242:android:de4f0201652b78fade27ab',
    messagingSenderId: '942862744242',
    projectId: 'multi-detection-system',
    storageBucket: 'multi-detection-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsUHsE7qIt38tWyKfOSHbEbAOp8e_x-U',
    appId: '1:942862744242:ios:f1c452c9eca1cfcbde27ab',
    messagingSenderId: '942862744242',
    projectId: 'multi-detection-system',
    storageBucket: 'multi-detection-system.firebasestorage.app',
    iosBundleId: 'com.example.multiDetectionSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsUHsE7qIt38tWyKfOSHbEbAOp8e_x-U',
    appId: '1:942862744242:ios:f1c452c9eca1cfcbde27ab',
    messagingSenderId: '942862744242',
    projectId: 'multi-detection-system',
    storageBucket: 'multi-detection-system.firebasestorage.app',
    iosBundleId: 'com.example.multiDetectionSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLzVhDqvWKTdgaV_0H2_nQ9wBRuTpydg',
    appId: '1:942862744242:web:13c7d3fb1c2d07e7de27ab',
    messagingSenderId: '942862744242',
    projectId: 'multi-detection-system',
    authDomain: 'multi-detection-system.firebaseapp.com',
    storageBucket: 'multi-detection-system.firebasestorage.app',
    measurementId: 'G-TKZH3TCX0G',
  );
}
